name: Daily README Update

on:
  schedule:
    - cron: '0 0 * * *'   # daily at midnight UTC
  workflow_dispatch:       # manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3️⃣ Update README with random quote
      - name: Update README
        run: |
          node -e "
          const fs = require('fs');
          const file = 'README.md';
          if (!fs.existsSync(file)) process.exit(0);

          const quotes = [
            'Code is like humor. When you have to explain it, it’s bad. — Cory House',
            'Experience is the name everyone gives to their mistakes. — Oscar Wilde',
            'First, solve the problem. Then, write the code. — John Johnson',
            'Simplicity is the soul of efficiency. — Austin Freeman',
            'Before software can be reusable it first has to be usable. — Ralph Johnson'
          ];

          const quote = quotes[Math.floor(Math.random() * quotes.length)];
          let content = fs.readFileSync(file, 'utf8');

          content = content.replace(/<!--DAILY_QUOTE-->.*$/, '<!--DAILY_QUOTE--> ' + quote);
          content = content.replace(/<!--LAST_UPDATED-->.*$/, '<!--LAST_UPDATED--> Updated on: ' + new Date().toUTCString());

          fs.writeFileSync(file, content);
          console.log('README updated successfully.');
          "

      # 4️⃣ Commit changes to a temporary branch
      - name: Commit changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b daily-readme-update || git checkout daily-readme-update
          git add README.md
          git diff --cached --quiet || git commit -m "Update daily dev quote and timestamp"

      # 5️⃣ Try to push directly
      - name: Push directly
        id: push
        run: |
          set -e
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          if git push origin HEAD:main; then
            echo "PUSH_SUCCESS=true" >> $GITHUB_ENV
          else
            echo "PUSH_SUCCESS=false" >> $GITHUB_ENV
          fi

      # 6️⃣ Fallback: Create PR if push fails
      - name: Create pull request if push blocked
        if: env.PUSH_SUCCESS == 'false'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update daily dev quote and timestamp"
          branch: daily-readme-update
          base: main
          title: "Daily README Update"
          body: "This PR updates the daily dev quote and timestamp in README.md"
