name: Daily README Quote Update

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update Daily Dev Quote
        run: |
          QUOTE=$(curl -s https://api.quotable.io/random | jq -r '.content')
          TIMESTAMP=$(date -u)
          # Replace placeholder in README
          sed -i "s|<!--DAILY_QUOTE-->|$QUOTE|g" README.md
          sed -i "s|<!--LAST_UPDATED-->|Updated on: $TIMESTAMP|g" README.md

      - name: Create or update pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          branch: daily-readme-update
          commit-message: "Daily README quote update"
          title: "Daily README quote update"
          body: "Automated update of Daily Dev Quote."
