name: Update Daily Dev Quote

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  update-quote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # ensures Node.js is installed

      - name: Pick a random quote
        id: quote
        run: |
          QUOTES=(
            "Code is like humor. When you have to explain it, it’s bad. — Cory House"
            "Experience is the name everyone gives to their mistakes. — Oscar Wilde"
            "First, solve the problem. Then, write the code. — John Johnson"
            "Simplicity is the soul of efficiency. — Austin Freeman"
            "Before software can be reusable it first has to be usable. — Ralph Johnson"
          )
          INDEX=$((RANDOM % ${#QUOTES[@]}))
          echo "QUOTE=${QUOTES[$INDEX]}" >> $GITHUB_ENV

      - name: Update README
        run: |
          FILE="README.md"
          if [ ! -f "$FILE" ]; then
            echo "README.md not found!"
            exit 1
          fi
          node -e "
            const fs = require('fs');
            const readme = fs.readFileSync('$FILE', 'utf8');
            const newReadme = readme.replace(/<!--DAILY_QUOTE-->.*$/, '<!--DAILY_QUOTE--> ' + process.env.QUOTE);
            fs.writeFileSync('$FILE', newReadme);
          "

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "Update daily dev quote"
          git push
