name: Daily README Update

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:    # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Run your update script
        run: |
          # Example: update README daily quote
          node update-readme.js

      - name: Create or update pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{secrets.PAT_TOKEN}}   # <-- Use the PAT secret here
          branch: daily-readme-update
          commit-message: "Daily README update"
          title: "Daily README update"
          body: "Automated daily update of README."
