name: Daily README Quote Update

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:    # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pick a random quote and update README
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")

          # Replace <!--DAILY_QUOTE--> with a random line from quotes.txt directly in Perl
          perl -i -pe '
            BEGIN {
              @q = `shuf -n 1 quotes.txt`;   # pick random quote
              chomp($q[0]);
            }
            s|<!--DAILY_QUOTE-->|$q[0]|' README.md

          # Update last updated timestamp
          perl -i -pe "s|<!--LAST_UPDATED-->|Updated on: $TIMESTAMP|" README.md

      - name: Commit & create/update pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          branch: daily-readme-update
          commit-message: "Daily README quote update"
          title: "Daily README quote update"
          body: "Automated update of Daily Dev Quote."
          auto-merge: true
          auto-merge-method: squash
