name: Update Daily README

on:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight UTC
  workflow_dispatch:      # allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Update README with random quote and timestamp
      - name: Update README
        run: |
          node -e "
          const fs = require('fs');
          const file = 'README.md';
          if (!fs.existsSync(file)) { 
            console.log('README.md not found, skipping update.'); 
            process.exit(0); 
          }

          const quotes = [
            'Code is like humor. When you have to explain it, it’s bad. — Cory House',
            'Experience is the name everyone gives to their mistakes. — Oscar Wilde',
            'First, solve the problem. Then, write the code. — John Johnson',
            'Simplicity is the soul of efficiency. — Austin Freeman',
            'Before software can be reusable it first has to be usable. — Ralph Johnson',
            'Programs must be written for people to read, and only incidentally for machines to execute. — Harold Abelson',
            'Any fool can write code that a computer can understand. Good programmers write code that humans can understand. — Martin Fowler',
            'Debugging is like being the detective in a crime movie where you are also the murderer. — Filipe Fortes',
            'The best way to get a project done faster is to start sooner. — Jim Highsmith',
            'Code never lies, comments sometimes do. — Ron Jeffries'
          ];

          const quote = quotes[Math.floor(Math.random() * quotes.length)];
          let content = fs.readFileSync(file, 'utf8');

          content = content.replace(/<!--DAILY_QUOTE-->.*$/, '<!--DAILY_QUOTE--> ' + quote);
          content = content.replace(/<!--LAST_UPDATED-->.*$/, '<!--LAST_UPDATED--> Updated on: ' + new Date().toUTCString());

          fs.writeFileSync(file, content);
          console.log('README updated successfully.');
          "

      # Step 4: Commit and push using GITHUB_TOKEN
      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "Update daily dev quote and timestamp"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin HEAD:main
