name: Daily README Quote Update

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:    # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pick a random quote and update README
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          QUOTE=$(shuf -n 1 quotes.txt)

          # Replace placeholders in README without adding backslashes
          sed -i "s|<!--DAILY_QUOTE-->|$QUOTE|" README.md
          sed -i "s|<!--LAST_UPDATED-->|Updated on: $TIMESTAMP|" README.md

      - name: Commit & create/update pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}   # Use your PAT token here
          branch: daily-readme-update
          commit-message: "Daily README quote update"
          title: "Daily README quote update"
          body: "Automated update of Daily Dev Quote."
          auto-merge: true
          auto-merge-method: squash
