name: Daily README Quote Update

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Pick a random quote and update README
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          QUOTE=$(shuf -n 1 quotes.txt)

          # Replace quote section
          perl -0777 -i -pe "s|(<!--DAILY_QUOTE-->)(.*?)(<!--/DAILY_QUOTE-->)|\1\n$QUOTE\n\3|s" README.md

          # Replace timestamp section
          perl -0777 -i -pe "s|(<!--LAST_UPDATED-->)(.*?)(<!--/LAST_UPDATED-->)|\1\nUpdated on: $TIMESTAMP\n\3|s" README.md

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Daily README quote update" || echo "No changes to commit"
          git push
