name: Update Daily README

on:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Update README with daily quote and timestamp
        run: |
          node -e "
            const fs = require('fs');
            const filePath = 'README.md';
            if (!fs.existsSync(filePath)) {
              console.error('README.md not found!');
              process.exit(1);
            }

            const quotes = [
              'Code is like humor. When you have to explain it, it’s bad. — Cory House',
              'Experience is the name everyone gives to their mistakes. — Oscar Wilde',
              'First, solve the problem. Then, write the code. — John Johnson',
              'Simplicity is the soul of efficiency. — Austin Freeman',
              'Before software can be reusable it first has to be usable. — Ralph Johnson'
            ];
            const quote = quotes[Math.floor(Math.random() * quotes.length)];

            let readme = fs.readFileSync(filePath, 'utf8');

            // Replace daily quote
            readme = readme.replace(/<!--DAILY_QUOTE-->.*$/, '<!--DAILY_QUOTE--> ' + quote);

            // Replace LAST_UPDATED
            const now = new Date().toUTCString();
            readme = readme.replace(/<!--LAST_UPDATED-->.*$/, '<!--LAST_UPDATED--> Updated on: ' + now);

            fs.writeFileSync(filePath, readme);
          "

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "Update daily dev quote and timestamp"
          git push
